[[pages]]
title = "Waterjets"
data = "https://opensheet.elk.sh/1NQGBDrmzIxoMZ7uvvdw0AxWmW4jO4ExOL8WC1AloJX0/Waterjets"

[[pages]]
title = "Transmissions"
data = "https://opensheet.elk.sh/1NQGBDrmzIxoMZ7uvvdw0AxWmW4jO4ExOL8WC1AloJX0/Transmissions"

[[pages]]
title = "Inboard Engines"
data = "https://opensheet.elk.sh/1NQGBDrmzIxoMZ7uvvdw0AxWmW4jO4ExOL8WC1AloJX0/Inboard"

[[pages]]
title = "Outboard Engines"
data = "https://opensheet.elk.sh/1NQGBDrmzIxoMZ7uvvdw0AxWmW4jO4ExOL8WC1AloJX0/Outboard"